### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Janonard** [Flumminard/the-Berry-Quest#23]
Wie wir ja abgesprochen haben, soll das Spiel von "the Berry Quest" in "Ambosia" umbenannt werden. Soll das so festgelegt werden und wenn ja, braucht das Spiel auch noch einen Untertitel, wie zum Beispiel "Ambosia - the adventures of Heron"?

Ich habe noch eine Frage, falls der Name geändert werden soll: Soll das Repository einfach umbennant oder ein neues erstellt werden?

**Comment by WitchKing1999** [comment]
1. Den "Untertitel" finde ich gut
2. Was heißt Repository?

**Comment by Janonard** [comment]
@WitchKing1999: Ich werde aus deiner Antwort nicht hundert prozentig schlau: Bist du jetzt damit einverstanden, dass "the Berry Quest" in "Ambosia" umbenannt wird oder hast du noch einen anderen Vorschlag?

Als Repository bezeichnet man einen Ordner in dem alle Dateien des Projekts liegen und von allen aufrufbar ist. In unserem Beispiel ist das der Ordner https://github.com/Flumminard/the-Berry-Quest.

**Comment by WitchKing1999** [comment]
@Janonard Ändere den Repository- Ordener in:
Ambosia- the Advetures of Heron
um!

**Comment by WitchKing1999** [comment]
Zum Schriftzug:
Soll er eher im Fantasy- Style gehalten werden mit Linien und golden oder eher Eckig und stählernd,
wie der Amboss im wort?

**Comment by Janonard** [comment]
Ich würde als Name des Repositories lieber "Ambosia" nehmen, dass ist einfacher zu tippen. Es geht nur halt darum, ob die alten Dateien, die ich sowieso vorhabe zu löschen, noch im Verlauf des Repos drin sein sollen.

Zum Schriftzug: Wenn wir den Untertitel mitnehmen, kann ja "Ambosia" schwungvoll und golden und der Untertitel kantig und stählern sein. Mach dazu bitte einen eigenen Issue!

**Comment by Janonard** [comment]
OK, da jetzt seid 3 Wochen niemand Einspruch gegen den Namen "Ambosia - the Adventures of Heron" erhoben hat, ist er jetzt gesetzt. Das Repository wird demnächst umbenannt.
